# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ccbdb6710f1528c19517b334fd493521ebd535e80fa26ace4f7c0fb2d915b9674b4785086aa0f49a363f394ba39cc683479c5f71d41637ba4e1404db8035cac

test:
  secret_key_base: 7573375b42b020c58fae4cca9fc92311430a38190a8fe24d1b4d94283adf1e78a2c65e9da854335cac4dcc8c128041a26b696682de9af7b1b5e43e1ec3ea2486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
